import AppKit

/// nspasteboard.org の標準マーカー型。参照: http://nspasteboard.org
extension NSPasteboard.PasteboardType {
    /// パスワードマネージャ等の機密データ。履歴に残さない。
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// 一時データ。記録も表示もしない。
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// 自動生成データ。履歴に残さない。
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// コピー元アプリの bundle id（UTF-8文字列）。情報用。
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")
}

/// 常に履歴へ記録しないマーカー（機密／一時／自動生成）。設定では無効化できない。
///
/// `.concealed` は以前 `ignoreConcealed` 設定で無効化できたが、README / PRIVACY.md が
/// 「パスワードは保存しない（never saved）」と無条件に約束している以上、設定で覆せる保護は
/// その約束と両立しない。プライバシーが本アプリの中核の訴求なので、強制条件へ格上げした。
let alwaysIgnoredMarkerTypes: Set<NSPasteboard.PasteboardType> = [.concealed, .transient, .autoGenerated]
