import AppKit

/// nspasteboard.org の標準マーカー型。参照: http://nspasteboard.org
extension NSPasteboard.PasteboardType {
    /// パスワードマネージャ等の機密データ。履歴に残さない。
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// 一時データ。記録も表示もしない。
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// 自動生成データ。履歴に残さない。
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// コピー元アプリの bundle id（UTF-8文字列）。情報用。
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")
}

/// 常に履歴へ記録しないマーカー（一時／自動生成）。設定に関わらず除外する。
let alwaysIgnoredMarkerTypes: Set<NSPasteboard.PasteboardType> = [.transient, .autoGenerated]

/// 機密（ConcealedType）は設定 `ignoreConcealed` が有効なときのみ除外するため別管理。
/// （`alwaysIgnoredMarkerTypes` ＋ 条件付き `.concealed` で旧 `ignoredMarkerTypes` 相当になる）
