import AppKit

/// nspasteboard.org の標準マーカー型。参照: http://nspasteboard.org
extension NSPasteboard.PasteboardType {
    /// パスワードマネージャ等の機密データ。履歴に残さない。
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// 一時データ。記録も表示もしない。
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    /// 自動生成データ。履歴に残さない。
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    /// コピー元アプリの bundle id（UTF-8文字列）。情報用。
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")
}

/// これらのマーカーが付いた変更は履歴に一切記録しない。
let ignoredMarkerTypes: Set<NSPasteboard.PasteboardType> = [.concealed, .transient, .autoGenerated]
